kind: pipeline
type: docker
name: deploy

steps:
  - name: compose
    image: docker/compose
    commands:
      - docker-compose up -d
    volumes:
      - name: docker_socket
        path: /var/run/docker.socket
volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.socket